# Generated by Django 5.2.1 on 2025-06-02 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricechangelog',
            old_name='change_date',
            new_name='changed_at',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='entered_amount_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('OVERDUE_STOCK', 'Overdue Stock'), ('PROFIT_LOSS', 'Profit/Loss Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pricechangelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scraptype',
            name='name',
            field=models.CharField(choices=[('Heavy', 'Heavy'), ('Light', 'Light'), ('Cast', 'Cast'), ('Soft', 'Soft'), ('Hard', 'Hard'), ('Brass', 'Brass'), ('Copper', 'Copper'), ('Battery', 'Battery'), ('Radiator', 'Radiator'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Basins', 'Basins')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scraptype',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='amount_given',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
