# Generated by Django 5.2.1 on 2025-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_change_date_pricechangelog_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraptype',
            name='name',
            field=models.CharField(choices=[('Heavy', 'Heavy'), ('Light', 'Light'), ('Cast', 'Cast'), ('Soft', 'Soft'), ('Hard', 'Hard'), ('Brass', 'Brass'), ('Copper', 'Copper'), ('Battery', 'Battery'), ('Radiator', 'Radiator'), ('Boots', 'Boots'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Sandals', 'Sandals'), ('Basins', 'Basins')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='amount_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
